<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="Lab13_2_css.css"?>
<!DOCTYPE quotes [
<!ELEMENT quotes (quote, author)>
<!ELEMENT quote (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT sign (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ENTITY ath "author: ">
<!ENTITY qout "Qoute: ">
]>

<quotes>

<quote>
<sign>&qout;</sign>Известно, что тесное общение оказывает большое взаимное влияние 
на образ мышления и манеры. Люди, чьи поступки мы непрерывно 
наблюдаем, чьи слова все время звучат у нас в ушах, непременно 
заставят нас, пусть и против нашей воли, поступать и говорить 
на их лад — медленно, постепенно, быть может, неуловимо, но такая 
перемена произойдет. Не берусь судить, как велика эта неуловимая 
сила общения, но случись цивилизованному человеку провести десяток 
лет среди дикарей, то, по моему твердому убеждению, к концу этого 
срока он и сам станет дикарем, хотя бы отчасти.
</quote>
<author>&ath;</author>
<name>Энн Бронте</name>

<quote>
<sign>&qout;</sign>Боги завидуют нам, потому что мы смертны. Любой момент нашей 
жизни может стать последним. Ведь жизнь ярче и прекраснее, 
когда она конечна. Ты никогда не будешь красивее, чем сейчас. 
И мы больше никогда не будем здесь
</quote>
<author>&ath;</author>
<name>Александр Скоробогатов</name>

<quote>
<sign>&qout;</sign>God is a woman
</quote>
<author>&ath;</author>
<name>Jo March</name>

</quotes>